### ISSUE TITLE
How can i use it in another plugin like notehighlight??

### ISSUE THREAD

**Issue by geniusC** [idvorkin/Vim-Keybindings-For-Onenote#44]
i change the script like these but it doesn't  work 
```
#IfWinActive ahk_class Framework::CFrame||NoteHighLight
#IfWinActive ahk_class Framework::CFrame||WindowsForms10.Window.8.app.0.21d1674_r6_ad1
```

**Comment by BlueDrink9** [comment]
At some point in the future I'll fork it for more general windows use.
In general, ahk_clases can be tough to get right. Have you tried using the AHK window spy to check the class is correct? Or try using windows?
Also, you can only have one \#IfWinActive line at a time. The lower one will be over-writing the higher one.
Otherwise, just getting rid of those two lines will let the script work all through windows.
